version: "3.9"
services:
  commande:
    container_name: commande
    image: commande
    build:
      context: ./commande  
    ports:
      - "8083:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/ 
    depends_on:
      - eureka

  eureka:
    container_name: eureka
    image: eureka    
    build:
      context: ./EurikaServer  
    hostname: serviceregistry
    ports:
      - "8761:8761"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/

  gateway:
    container_name: gateway
    image: apigateway
    build:
      context: ./Gateway  
    ports:
      - "8091:8091"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - eureka
      - commande
